# Meta Data for SEO

## Homepage
title = "Debugging Your Brain"
titleSeparator = "-"
titleAddition = "Clear, concise applied psychology and self-help"
description = "This book brings together two parts of Casey's background: psychology and software development. Casey studied neurobiology at Yale University, and he is a co-author on several neurobiology papers. He has also worked in software development for 10 years, including at Heroku. Casey is an independent author based in Washington, DC."

## Open Graph + Twitter Cards
images = ["brainimage.png"]
twitterSite = "heycaseywattsup"
twitterCreator = "heycaseywattsup"
facebookAuthor = "debuggingyourbrain"
facebookPublisher = "debuggingyourbrain"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "brainimage.png"
schemaTwitter = "https://twitter.com/heycaseywattsup"
schemaLinkedIn = "https://www.linkedin.com/in/caseywatts/"
schemaGitHub = "https://github.com/caseywatts"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#5F4A9E"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/caseywatts/dyb-doks"
editPage = false
